SET DEFINE OFF
ALTER SESSION SET CURRENT_SCHEMA = ITERIA_AI;
-- ============================================================================
-- QUESTIONNAIRE BACKEND: EDIT-APPROVAL WORKFLOW
-- Requires INSIGHT_07 (insight_questions, insight_clients, insight_client_answers).
--
-- Policy: the FIRST time a question is answered for a client, it writes
-- directly to insight_client_answers -- normal data entry by whoever's
-- doing the intake needs no approval gate. Once a question already HAS an
-- answer, changing it goes through insight_answer_change_requests instead
-- of overwriting directly, and only lands in insight_client_answers once
-- someone approves it. This is what stops a value from being quietly
-- edited after the fact ("pencil-whipped") without a record of the change.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. TABLE: INSIGHT_ANSWER_CHANGE_REQUESTS
-- ----------------------------------------------------------------------------
CREATE TABLE insight_answer_change_requests (
    request_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       VARCHAR2(40) NOT NULL,
    question_id     VARCHAR2(20) NOT NULL,
    previous_value  CLOB,                                -- snapshot of what was there before, for the audit trail
    proposed_value  CLOB,
    submitted_by    VARCHAR2(100) NOT NULL,
    submitted_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status          VARCHAR2(10) DEFAULT 'PENDING' NOT NULL,
    reviewed_by     VARCHAR2(100),
    reviewed_at     TIMESTAMP WITH TIME ZONE,
    review_note     VARCHAR2(500),
    CONSTRAINT fk_insight_chgreq_client FOREIGN KEY (client_id) REFERENCES insight_clients(client_id) ON DELETE CASCADE,
    CONSTRAINT fk_insight_chgreq_question FOREIGN KEY (question_id) REFERENCES insight_questions(question_id),
    CONSTRAINT chk_insight_chgreq_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);
CREATE INDEX idx_insight_chgreq_pending ON insight_answer_change_requests (client_id, status);

COMMENT ON TABLE insight_answer_change_requests IS 'Proposed edits to an already-answered question. Only insight_client_answers reflects approved values -- this table is the audit trail of who proposed/approved/rejected each change.';

-- ----------------------------------------------------------------------------
-- 2. PACKAGE SPEC: PKG_INSIGHT_ANSWERS
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE pkg_insight_answers AS

    -- First answer for (client_id, question_id): writes directly.
    -- Answer already exists: creates a PENDING change request instead and
    -- leaves insight_client_answers untouched. x_out_status returns
    -- 'SAVED' or 'PENDING_APPROVAL' so the caller (ORDS/app) knows which
    -- happened.
    PROCEDURE record_answer(
        p_client_id      IN VARCHAR2,
        p_question_id    IN VARCHAR2,
        p_value          IN CLOB,
        p_actor          IN VARCHAR2,
        p_is_skipped     IN NUMBER DEFAULT 0,
        x_out_status     OUT VARCHAR2
    );

    PROCEDURE approve_change_request(
        p_request_id     IN NUMBER,
        p_reviewer       IN VARCHAR2,
        p_note           IN VARCHAR2 DEFAULT NULL
    );

    PROCEDURE reject_change_request(
        p_request_id     IN NUMBER,
        p_reviewer       IN VARCHAR2,
        p_note           IN VARCHAR2 DEFAULT NULL
    );

END pkg_insight_answers;
/
