SET DEFINE OFF
ALTER SESSION SET CURRENT_SCHEMA = ITERIA_AI;
-- ============================================================================
-- QUESTIONNAIRE BACKEND: DOCUMENT STORAGE + RETRIEVAL
-- Requires INSIGHT_07 (insight_clients).
--
-- Design: raw files live in OCI Object Storage, not in the database -- this
-- table only stores a pointer (bucket/object name) plus metadata and
-- processing status. Chunking + embedding happens as an async background
-- job (upload should never block on it), and results land in
-- insight_document_chunks using Oracle 23ai's native VECTOR type, so there's
-- no separate vector database to run and maintain. The embedding model
-- (Cohere via OCI Generative AI, or another) is an application-layer
-- choice -- nothing here depends on which one is used, only on the
-- resulting vector's dimension matching the column definition below.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. TABLE: INSIGHT_CLIENT_DOCUMENTS (Object Storage pointer + metadata)
-- ----------------------------------------------------------------------------
CREATE TABLE insight_client_documents (
    document_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id         VARCHAR2(40) NOT NULL,
    file_name         VARCHAR2(500) NOT NULL,
    mime_type         VARCHAR2(100),
    size_bytes        NUMBER,
    bucket_name       VARCHAR2(200) NOT NULL,
    object_name       VARCHAR2(1000) NOT NULL,            -- OCI Object Storage object path
    processing_status VARCHAR2(20) DEFAULT 'UPLOADED' NOT NULL,
    processing_error  VARCHAR2(1000),
    uploaded_by       VARCHAR2(100),
    uploaded_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_insight_docs_client FOREIGN KEY (client_id) REFERENCES insight_clients(client_id) ON DELETE CASCADE,
    CONSTRAINT chk_insight_docs_status CHECK (processing_status IN ('UPLOADED', 'CHUNKING', 'EMBEDDED', 'ERROR'))
);
CREATE INDEX idx_insight_docs_client ON insight_client_documents (client_id, uploaded_at DESC);
CREATE INDEX idx_insight_docs_status ON insight_client_documents (processing_status);

COMMENT ON TABLE insight_client_documents IS 'Metadata + Object Storage pointer for client-uploaded documents. Raw file bytes never live in the database.';

-- ----------------------------------------------------------------------------
-- 2. TABLE: INSIGHT_DOCUMENT_CHUNKS (chunked text + embeddings)
-- ----------------------------------------------------------------------------
-- NOTE: VECTOR(1024, FLOAT32) assumes a 1024-dimension embedding model
-- (matches Cohere embed-english-v3.0 via OCI Generative AI). If a different
-- embedding model is used, change the dimension here to match -- it must
-- agree with whatever the ingestion pipeline actually produces.
CREATE TABLE insight_document_chunks (
    chunk_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id     NUMBER NOT NULL,
    client_id       VARCHAR2(40) NOT NULL,                -- denormalized from the parent document for simpler filtering
    chunk_index     NUMBER NOT NULL,
    chunk_text      CLOB NOT NULL,
    embedding       VECTOR(1024, FLOAT32),
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_insight_chunks_document FOREIGN KEY (document_id) REFERENCES insight_client_documents(document_id) ON DELETE CASCADE,
    CONSTRAINT fk_insight_chunks_client FOREIGN KEY (client_id) REFERENCES insight_clients(client_id) ON DELETE CASCADE,
    CONSTRAINT uq_insight_chunks_doc_idx UNIQUE (document_id, chunk_index)
);
CREATE INDEX idx_insight_chunks_client ON insight_document_chunks (client_id);

COMMENT ON TABLE insight_document_chunks IS 'Chunked text + vector embeddings per document, for retrieval. Add a vector index (HNSW or IVF, via CREATE VECTOR INDEX) once real document volume justifies one -- skipped here since the right index type/params depend on eventual data volume and query patterns, which are not known yet.';
