ALTER SESSION SET CURRENT_SCHEMA = ITERIA_AI;
-- ============================================================================
-- INSIGHT API CONFIGURATION
--
-- The ORDS handlers check a caller-supplied api_key against a stored value.
-- They used to read a table named API_CONFIGURATION, which INSIGHT does not
-- own and no migration here creates -- it belongs to something else sharing
-- this schema. That made every INSIGHT endpoint depend on another product's
-- object being present and shaped as expected, and when it was not, the
-- handlers failed with ORDS-25001 / HTTP 555.
--
-- This table is INSIGHT's own. Nothing outside INSIGHT reads or writes it.
--
-- Behaviour of the check, unchanged: if no active row exists, no key is
-- required. Deactivate every row to open the endpoints; keep exactly one
-- active row to require it.
-- ============================================================================

CREATE TABLE insight_api_config (
    config_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key     VARCHAR2(200) NOT NULL,
    is_active   VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    description VARCHAR2(400),
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_insight_api_cfg_active CHECK (is_active IN ('Y', 'N'))
);

COMMENT ON TABLE insight_api_config IS 'API keys accepted by the INSIGHT ORDS module. No active row means no key is required.';

-- Only one key may be active at a time: the handlers select a single row,
-- so two active rows would make which one wins depend on row order.
CREATE UNIQUE INDEX uq_insight_api_cfg_active
    ON insight_api_config (CASE WHEN is_active = 'Y' THEN 1 END);

-- Seeds the key the deployed container already sends, so the check passes
-- without any further configuration. Rotate by updating this row; the
-- container reads ORDS_API_KEY from the environment first, so a rotation
-- needs no rebuild.
MERGE INTO insight_api_config t
USING (SELECT 'vld8x2k9mPqR7sNjT4hW' AS api_key FROM dual) s
   ON (t.api_key = s.api_key)
WHEN NOT MATCHED THEN
  INSERT (api_key, is_active, description)
  VALUES (s.api_key, 'Y', 'Initial build-out key. Rotate before this holds real client data.');

COMMIT;
