ALTER SESSION SET CURRENT_SCHEMA = ITERIA_AI;
-- ============================================================================
-- ORACLE DATABASE SCHEMA A: DATA LAYER
-- Target Environment: Oracle Database 19c / 21c / 23c / Autonomous DB
-- Deploys into ITERIA_AI (ALTER SESSION SET CURRENT_SCHEMA above). Run
-- while connected as ADMIN: the target database has a single login, and
-- ADMIN has rights to create objects in ITERIA_AI.
-- Description: Physical state storage for 26-node AI Matrix and Activity Audits.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. TABLE: AI_BOARDS (Matrix Board Sessions)
-- ----------------------------------------------------------------------------
CREATE TABLE insight_boards (
    board_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_name      VARCHAR2(100) NOT NULL,
    description     VARCHAR2(400),
    status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_insight_board_status CHECK (status IN ('ACTIVE', 'ARCHIVED', 'MAINTENANCE'))
);

COMMENT ON TABLE insight_boards IS 'Holds metadata for 26-node matrix operational boards.';

-- ----------------------------------------------------------------------------
-- 2. TABLE: AI_NODES_26 (Physical State Table for Nodes 1 through 26)
-- ----------------------------------------------------------------------------
CREATE TABLE insight_nodes_26 (
    node_id              NUMBER(2) NOT NULL,
    board_id             NUMBER NOT NULL,
    node_code            VARCHAR2(10) NOT NULL,
    node_letter          VARCHAR2(1) NOT NULL,
    node_name            VARCHAR2(100) NOT NULL,
    category             VARCHAR2(30) NOT NULL,
    current_status       VARCHAR2(20) DEFAULT 'IDLE' NOT NULL,
    state_value          NUMBER(10,4) DEFAULT 0.0000 NOT NULL,
    payload_json         CLOB,
    priority             NUMBER(2) DEFAULT 1 NOT NULL,
    processing_count     NUMBER(10) DEFAULT 0 NOT NULL,
    last_event_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- Strict State Machine Constraints
    CONSTRAINT pk_insight_nodes_26 PRIMARY KEY (board_id, node_id),
    CONSTRAINT fk_insight_nodes_board FOREIGN KEY (board_id) REFERENCES insight_boards(board_id) ON DELETE CASCADE,
    CONSTRAINT chk_insight_node_range CHECK (node_id BETWEEN 1 AND 26),
    CONSTRAINT chk_insight_node_status CHECK (current_status IN (
        'IDLE', 'PROCESSING', 'ACTIVE', 'EVALUATING', 'CASCADE', 'LOCKED', 'COMPLETED', 'ERROR'
    )),
    CONSTRAINT chk_insight_node_json CHECK (payload_json IS JSON (LAX))
);

CREATE INDEX idx_insight_nodes_status ON insight_nodes_26 (board_id, current_status);
CREATE INDEX idx_insight_nodes_code ON insight_nodes_26 (node_code);

COMMENT ON TABLE insight_nodes_26 IS 'Stores physical state, JSON payloads, and status for Nodes 1..26.';

-- ----------------------------------------------------------------------------
-- 3. TABLE: AI_BOARD_ACTIVITY_LOG (Execution Audit Trail)
-- ----------------------------------------------------------------------------
CREATE TABLE insight_board_activity_log (
    log_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id            NUMBER NOT NULL,
    node_id             NUMBER(2) NOT NULL,
    event_type          VARCHAR2(50) NOT NULL,
    payload_sent        CLOB,
    payload_received    CLOB,
    execution_time_ms   NUMBER(10,2),
    plsql_procedure     VARCHAR2(100),
    status              VARCHAR2(20) DEFAULT 'SUCCESS' NOT NULL,
    log_timestamp       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_insight_log_board FOREIGN KEY (board_id) REFERENCES insight_boards(board_id) ON DELETE CASCADE,
    CONSTRAINT chk_insight_log_node CHECK (node_id BETWEEN 1 AND 26),
    CONSTRAINT chk_insight_log_status CHECK (status IN ('SUCCESS', 'WARNING', 'ERROR'))
);

CREATE INDEX idx_insight_log_board_time ON insight_board_activity_log (board_id, log_timestamp DESC);

-- ----------------------------------------------------------------------------
-- 4. TRIGGER: TRG_AI_NODES_26_UPDATED
-- Auto-updates timestamp on state modifications.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_insight_nodes_26_updated
BEFORE UPDATE ON insight_nodes_26
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/
