ALTER SESSION SET CURRENT_SCHEMA = ITERIA_AI;
-- ============================================================================
-- CLIENT PROFILE AND ADDITIONAL INFORMATION
--
-- Everything captured so far has been an answer to a question the
-- questionnaire asked. Two things a client engagement produces do not fit
-- that shape:
--
-- 1. The company's own details -- who they are and who to call. Columns for
--    this already exist on insight_clients (company_name, primary_contact),
--    but nothing has ever written primary_contact: the only writer is the
--    PUT handler, which sets the name and nothing else. So the column is a
--    promise the API never kept. No schema change is needed for it; the
--    endpoint is what was missing.
--
-- 2. Anything the client says that no question asked. Today that has
--    nowhere to go, so it either gets forced into whatever answer looks
--    closest -- corrupting a field that feeds a Fusion setup value -- or it
--    is lost. Both are worse than a note.
--
-- Notes are deliberately NOT answers, and this table is separate for that
-- reason:
--
--   * They feed no setup field, so they need no question_id, no typing and
--     no option list.
--   * They are additive. A second note does not replace the first, so there
--     is nothing to route through the approval workflow -- that workflow
--     exists because overwriting an answer destroys the previous value, and
--     appending destroys nothing.
--   * Editing one is an ordinary update. Archiving keeps the row, matching
--     how a client DELETE archives rather than deletes.
--
-- They do carry the same provenance as answers, so a reader can tell a note
-- the assistant proposed from one a consultant typed.
-- ============================================================================

CREATE TABLE insight_client_notes (
    note_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   VARCHAR2(40) NOT NULL,
    note_text   CLOB NOT NULL,
    note_source VARCHAR2(20) DEFAULT 'CONSULTANT' NOT NULL,
    created_by  VARCHAR2(100),
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_archived NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_insight_note_client FOREIGN KEY (client_id)
        REFERENCES insight_clients(client_id) ON DELETE CASCADE,
    CONSTRAINT chk_insight_note_source
        CHECK (note_source IN ('SALES_INTAKE', 'AI_ASSIST', 'CONSULTANT')),
    CONSTRAINT chk_insight_note_archived CHECK (is_archived IN (0, 1))
);

-- note_text carries no CHECK constraint by design: Oracle does not allow
-- them on LOB columns. NOT NULL is the one constraint a LOB accepts, and an
-- empty note is rejected by the API before it reaches here.

-- The screen always reads one client's live notes, newest first.
CREATE INDEX idx_insight_notes_client
    ON insight_client_notes (client_id, is_archived, created_at DESC);

CREATE OR REPLACE TRIGGER trg_insight_notes_updated
BEFORE UPDATE ON insight_client_notes
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

COMMENT ON TABLE insight_client_notes IS 'Free-form information about a client that no question asked. Additive and never overwritten, so no approval workflow applies.';
COMMENT ON COLUMN insight_client_notes.note_source IS 'Who produced this note: SALES_INTAKE, AI_ASSIST or CONSULTANT. Same vocabulary as insight_client_answers.answer_source.';
COMMENT ON COLUMN insight_client_notes.is_archived IS '1 = hidden from the client screen. The row is kept, matching how archiving a client keeps its answers.';

COMMENT ON COLUMN insight_clients.primary_contact IS 'Free-text name of the person to call. Written by PUT /insight/clients/:client_id; distinct from the intake questions about contact details, which feed the handoff.';

COMMIT;
