ALTER SESSION SET CURRENT_SCHEMA = ITERIA_AI;
-- ============================================================================
-- CONFIGURATION UPDATES
--
-- A client engagement does not end when the questionnaire is finished. They
-- buy a subsidiary, add a module, replace the system they are migrating
-- from -- and the configuration that was handed over is now wrong.
--
-- Editing the affected answers is already possible. What was missing is the
-- record of WHY: a configuration handed over in March and another in
-- September differ for a reason, and "the answers changed at some point"
-- does not tell an implementation team which change they are looking at.
--
-- One row per configuration update: what changed, who said so, when, and how
-- many answers it touched. That last count is what distinguishes an update
-- that reshaped the client's setup from one that corrected a phone number.
--
-- Deliberately NOT the same thing as:
--
--   insight_answer_change_requests  one proposed edit to one answer, awaiting
--                                   approval. Mechanical, per-question.
--   insight_client_notes            something the client said that no
--                                   question asked. Additive, feeds nothing.
--
-- This is the business event those sit underneath: the reason a new
-- configuration was produced at all.
-- ============================================================================

CREATE TABLE insight_config_updates (
    update_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       VARCHAR2(40) NOT NULL,
    change_summary  CLOB NOT NULL,
    requested_by    VARCHAR2(100),
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    answers_changed NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT fk_insight_cfgupd_client FOREIGN KEY (client_id)
        REFERENCES insight_clients(client_id) ON DELETE CASCADE,
    CONSTRAINT chk_insight_cfgupd_changed CHECK (answers_changed >= 0)
);

-- change_summary carries no CHECK: Oracle allows none on a LOB column. An
-- empty summary is refused by the API before it reaches here, for the same
-- reason an empty note is -- an update with no stated reason is exactly the
-- thing this table exists to prevent.

CREATE INDEX idx_insight_cfgupd_client
    ON insight_config_updates (client_id, created_at DESC);

COMMENT ON TABLE insight_config_updates IS 'One row per configuration update: why a client''s configuration was regenerated. The business event behind the answer edits, not the edits themselves.';
COMMENT ON COLUMN insight_config_updates.answers_changed IS 'How many answers had been edited when this update was recorded. Distinguishes a reshaped setup from a corrected phone number.';

COMMIT;
