ALTER SESSION SET CURRENT_SCHEMA = ITERIA_AI;
-- ============================================================================
-- WHERE AN IMPORTED ANSWER CAME FROM
--
-- Existing clients have no discovery interview to reconstruct. The engagement
-- happened years ago and a hand-filled spreadsheet is the only record of it,
-- so the way those clients get into INSIGHT is by reading that spreadsheet.
--
-- An answer read out of a document is not the same kind of fact as one a
-- consultant gave, and the record has to be able to say which it is:
--
--   DOCUMENT_IMPORT   read out of an uploaded file by a machine
--   AI_ASSIST         proposed by the assistant from something said
--   SALES_INTAKE      captured during the questionnaire
--   CONSULTANT        entered or corrected by the implementation team
--
-- The evidence matters more than the label. Every imported answer carries the
-- cell it was taken from and the result of checking that cell, so the
-- question "why does this client's file say that" has an answer that does not
-- depend on anyone's memory. An import nobody can audit produces a client file
-- full of plausible unverified values, which is worse than an empty one --
-- an empty file is visibly empty, and a confident wrong one is not.
--
-- Verification is recorded rather than enforced, deliberately. The service
-- discards answers citing nothing or citing empty cells before they ever
-- reach here, but an answer whose cited cell exists and simply does not
-- support it is kept and marked, because a reviewer has to see it to reject
-- it. Silently dropping it would hide the one case worth a human's attention.
-- ============================================================================

ALTER TABLE insight_client_answers DROP CONSTRAINT chk_insight_ans_source;

ALTER TABLE insight_client_answers ADD CONSTRAINT chk_insight_ans_source
    CHECK (answer_source IN ('SALES_INTAKE', 'AI_ASSIST', 'CONSULTANT', 'DOCUMENT_IMPORT'));

COMMENT ON COLUMN insight_client_answers.answer_source IS 'Who produced this answer: SALES_INTAKE, AI_ASSIST, CONSULTANT or DOCUMENT_IMPORT.';

-- One row per cell an imported answer was drawn from. A separate table rather
-- than a column, because an answer routinely comes from several cells -- "six
-- segments, these names, these lengths" is a dozen of them -- and a delimited
-- list in a column would be unqueryable the first time anyone asks which
-- answers came from a sheet that turned out to be wrong.
CREATE TABLE insight_answer_evidence (
    evidence_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       VARCHAR2(40) NOT NULL,
    question_id     VARCHAR2(20) NOT NULL,
    document_id     NUMBER,
    cell_ref        VARCHAR2(200) NOT NULL,
    cell_value      VARCHAR2(1000),
    verification    VARCHAR2(20) DEFAULT 'supported' NOT NULL,
    recorded_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_insight_evid_client FOREIGN KEY (client_id)
        REFERENCES insight_clients(client_id) ON DELETE CASCADE,
    CONSTRAINT fk_insight_evid_question FOREIGN KEY (question_id)
        REFERENCES insight_questions(question_id),
    CONSTRAINT fk_insight_evid_document FOREIGN KEY (document_id)
        REFERENCES insight_client_documents(document_id) ON DELETE SET NULL,
    CONSTRAINT chk_insight_evid_verification
        CHECK (verification IN ('supported', 'unsupported'))
);

-- The question a reviewer actually asks is "where did this client's answer to
-- this question come from", so that is the index.
CREATE INDEX idx_insight_evidence_answer
    ON insight_answer_evidence (client_id, question_id);

COMMENT ON TABLE insight_answer_evidence IS 'Cells an imported answer was drawn from, with the result of checking each. Makes "why does the file say that" answerable without relying on memory.';
COMMENT ON COLUMN insight_answer_evidence.cell_ref IS 'A1-style reference including the sheet, e.g. Ledger!F9.';
COMMENT ON COLUMN insight_answer_evidence.verification IS 'supported = the cited cell shares content with the answer. unsupported = the cell exists but does not back it up; kept and flagged so a reviewer can reject it.';

-- Uploaded files can live in the database rather than object storage.
--
-- V10 required both bucket_name and object_name because it assumed OCI Object
-- Storage. Standing that up is a bucket, a policy and a second failure mode,
-- for files of a few hundred kilobytes that only ever get read while someone
-- reviews an import. Both columns become optional so a workbook can simply be
-- attached to its client; the object-storage path still works unchanged for
-- anything large enough to deserve it.
ALTER TABLE insight_client_documents MODIFY (bucket_name VARCHAR2(200) NULL);
ALTER TABLE insight_client_documents MODIFY (object_name VARCHAR2(1000) NULL);

ALTER TABLE insight_client_documents ADD (file_content BLOB);

COMMENT ON COLUMN insight_client_documents.file_content IS 'The uploaded file, when it is held in the database rather than object storage. For a client whose only record is a spreadsheet, the file IS the provenance and is kept with them.';

-- ----------------------------------------------------------------------------
-- The gate, widened to cover the new source.
--
-- V25 queued a change only when the source was AI_ASSIST. A DOCUMENT_IMPORT
-- answer would therefore have applied straight over an existing value, so
-- re-importing a client's updated spreadsheet could silently replace answers a
-- consultant had confirmed. Everything else about the procedure is unchanged
-- from V25.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY pkg_insight_answers AS

    PROCEDURE record_answer(
        p_client_id      IN VARCHAR2,
        p_question_id    IN VARCHAR2,
        p_value          IN CLOB,
        p_actor          IN VARCHAR2,
        p_is_skipped     IN NUMBER DEFAULT 0,
        x_out_status     OUT VARCHAR2,
        p_source         IN VARCHAR2 DEFAULT 'SALES_INTAKE',
        p_is_unknown     IN NUMBER DEFAULT 0
    ) IS
        v_existing_count NUMBER;
        v_has_value      NUMBER;
        v_unknown        NUMBER := NVL(p_is_unknown, 0);
        v_source         VARCHAR2(20) := NVL(p_source, 'SALES_INTAKE');
        v_value          CLOB   := p_value;
    BEGIN
        IF p_client_id IS NULL OR p_question_id IS NULL THEN
            RAISE_APPLICATION_ERROR(-20101, 'client_id and question_id are required.');
        END IF;

        -- "Not known yet" and a value are mutually exclusive; the column
        -- constraint enforces it, so normalise here rather than letting a
        -- caller trip over it.
        IF v_unknown = 1 THEN
            v_value := NULL;
        END IF;

        SELECT COUNT(*)
          INTO v_existing_count
          FROM insight_client_answers
         WHERE client_id = p_client_id
           AND question_id = p_question_id;

        IF v_existing_count = 0 THEN
            INSERT INTO insight_client_answers (
                client_id, question_id, answer_value, answered_by, answered_at,
                is_skipped, answer_source, is_unknown
            ) VALUES (
                p_client_id, p_question_id, v_value, p_actor, CURRENT_TIMESTAMP,
                NVL(p_is_skipped, 0), v_source, v_unknown
            );
            x_out_status := 'SAVED';
            RETURN;
        END IF;

        -- Is there an answer of record here, or only a row? A skipped or
        -- "not known yet" row exists but asserts nothing. DBMS_LOB.GETLENGTH
        -- rather than a length comparison, since answer_value is a CLOB and
        -- an empty CLOB is not NULL.
        SELECT COUNT(*)
          INTO v_has_value
          FROM insight_client_answers
         WHERE client_id = p_client_id
           AND question_id = p_question_id
           AND answer_value IS NOT NULL
           AND DBMS_LOB.GETLENGTH(answer_value) > 0;

        -- Straight through, none of which overwrites an answer: a skip, a
        -- "not known yet", and the first real value for a question that had
        -- none.
        IF NVL(p_is_skipped, 0) = 1 OR v_unknown = 1 OR v_has_value = 0 THEN
            UPDATE insight_client_answers
               SET is_skipped    = NVL(p_is_skipped, 0),
                   is_unknown    = v_unknown,
                   answer_value  = CASE
                                     WHEN v_unknown = 1 THEN NULL
                                     WHEN NVL(p_is_skipped, 0) = 1 AND v_value IS NULL THEN answer_value
                                     ELSE v_value
                                   END,
                   answer_source = v_source,
                   answered_by   = p_actor,
                   answered_at   = CURRENT_TIMESTAMP
             WHERE client_id = p_client_id
               AND question_id = p_question_id;
            x_out_status := 'SAVED';
            RETURN;
        END IF;

        -- An answer of record is being changed. Who is asking decides.
        --
        -- A machine is a machine whether it read a document or interpreted
        -- something spoken: neither gets to overwrite a value a person put
        -- there. Without DOCUMENT_IMPORT in this list, re-importing an
        -- updated spreadsheet over an existing client would quietly replace
        -- confirmed answers -- the exact failure the workflow exists to stop.
        IF v_source IN ('AI_ASSIST', 'DOCUMENT_IMPORT') THEN
            INSERT INTO insight_answer_change_requests (
                client_id, question_id, previous_value, proposed_value,
                submitted_by, submitted_at, status
            )
            SELECT p_client_id, p_question_id, answer_value, v_value,
                   p_actor, CURRENT_TIMESTAMP, 'PENDING'
              FROM insight_client_answers
             WHERE client_id = p_client_id
               AND question_id = p_question_id;
            x_out_status := 'PENDING_APPROVAL';
        ELSE
            -- Applied, and recorded. The APPLIED row is what makes "what did
            -- this say before, and who changed it" still answerable -- the
            -- audit trail survives even though the approval step does not.
            INSERT INTO insight_answer_change_requests (
                client_id, question_id, previous_value, proposed_value,
                submitted_by, submitted_at, status, reviewed_by, reviewed_at, review_note
            )
            SELECT p_client_id, p_question_id, answer_value, v_value,
                   p_actor, CURRENT_TIMESTAMP, 'APPLIED', p_actor, CURRENT_TIMESTAMP,
                   'Applied directly: consultant edit.'
              FROM insight_client_answers
             WHERE client_id = p_client_id
               AND question_id = p_question_id;

            UPDATE insight_client_answers
               SET answer_value  = v_value,
                   answer_source = v_source,
                   answered_by   = p_actor,
                   answered_at   = CURRENT_TIMESTAMP,
                   is_skipped    = 0,
                   is_unknown    = 0,
                   -- A changed answer is no longer the confirmed one.
                   -- Leaving is_confirmed set would certify a value nobody
                   -- has looked at.
                   is_confirmed  = 0,
                   confirmed_by  = NULL,
                   confirmed_at  = NULL
             WHERE client_id = p_client_id
               AND question_id = p_question_id;
            x_out_status := 'SAVED';
        END IF;
    END record_answer;

    PROCEDURE approve_change_request(
        p_request_id     IN NUMBER,
        p_reviewer       IN VARCHAR2,
        p_note           IN VARCHAR2 DEFAULT NULL
    ) IS
        v_client_id      VARCHAR2(40);
        v_question_id    VARCHAR2(20);
        v_proposed_value CLOB;
        v_status         VARCHAR2(10);
    BEGIN
        SELECT client_id, question_id, proposed_value, status
          INTO v_client_id, v_question_id, v_proposed_value, v_status
          FROM insight_answer_change_requests
         WHERE request_id = p_request_id
         FOR UPDATE;

        IF v_status != 'PENDING' THEN
            RAISE_APPLICATION_ERROR(-20102, 'Change request ' || p_request_id || ' is already ' || v_status || '.');
        END IF;

        UPDATE insight_client_answers
           SET answer_value = v_proposed_value,
               answered_by = p_reviewer,
               answered_at = CURRENT_TIMESTAMP,
               is_skipped = 0,
               is_unknown = 0
         WHERE client_id = v_client_id
           AND question_id = v_question_id;

        UPDATE insight_answer_change_requests
           SET status = 'APPROVED',
               reviewed_by = p_reviewer,
               reviewed_at = CURRENT_TIMESTAMP,
               review_note = p_note
         WHERE request_id = p_request_id;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20103, 'Change request ' || p_request_id || ' not found.');
    END approve_change_request;

    PROCEDURE reject_change_request(
        p_request_id     IN NUMBER,
        p_reviewer       IN VARCHAR2,
        p_note           IN VARCHAR2 DEFAULT NULL
    ) IS
        v_status VARCHAR2(10);
    BEGIN
        SELECT status
          INTO v_status
          FROM insight_answer_change_requests
         WHERE request_id = p_request_id
         FOR UPDATE;

        IF v_status != 'PENDING' THEN
            RAISE_APPLICATION_ERROR(-20102, 'Change request ' || p_request_id || ' is already ' || v_status || '.');
        END IF;

        UPDATE insight_answer_change_requests
           SET status = 'REJECTED',
               reviewed_by = p_reviewer,
               reviewed_at = CURRENT_TIMESTAMP,
               review_note = p_note
         WHERE request_id = p_request_id;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20103, 'Change request ' || p_request_id || ' not found.');
    END reject_change_request;

    PROCEDURE confirm_answer(
        p_client_id      IN VARCHAR2,
        p_question_id    IN VARCHAR2,
        p_reviewer       IN VARCHAR2
    ) IS
    BEGIN
        UPDATE insight_client_answers
           SET is_confirmed = 1,
               confirmed_by = p_reviewer,
               confirmed_at = CURRENT_TIMESTAMP
         WHERE client_id = p_client_id
           AND question_id = p_question_id;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20104,
                'No answer to confirm for ' || p_client_id || ' / ' || p_question_id || '.');
        END IF;
    END confirm_answer;

END pkg_insight_answers;
/

COMMIT;
