ALTER SESSION SET CURRENT_SCHEMA = ITERIA_AI;
-- ============================================================================
-- ORACLE DATABASE SCHEMA B: BEHAVIOR AND EDL LAYER
-- Target Environment: Oracle Database 19c / 21c / 23c / Autonomous DB
-- Deploys into ITERIA_AI, same as INSIGHT_01 -- pkg_insight_board_engine
-- queries this table and the data-layer tables together without schema
-- qualification (both live in ITERIA_AI).
-- Description: EDL Event Definition Language rules engine and PL/SQL package logic.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. TABLE: AI_EDL_RULES (Event Definition Language Storage)
-- ----------------------------------------------------------------------------
CREATE TABLE insight_edl_rules (
    rule_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code        VARCHAR2(50) UNIQUE NOT NULL,
    rule_name        VARCHAR2(150) NOT NULL,
    source_node_id   NUMBER(2), -- NULL or 0 represents ALL source nodes
    event_type       VARCHAR2(50) NOT NULL,
    condition_expr   VARCHAR2(4000) NOT NULL,
    target_node_list VARCHAR2(200) NOT NULL, -- Comma-separated list e.g. '2,5,12'
    action_type      VARCHAR2(50) NOT NULL,
    action_params    CLOB,
    is_active        VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_insight_edl_is_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT chk_insight_edl_event_type CHECK (event_type IN (
        'ON_TRIGGER', 'ON_THRESHOLD_EXCEEDED', 'ON_STATE_CHANGE', 'ON_CASCADE_PULSE', 'ON_ERROR', 'ON_SECURITY_ALERT'
    )),
    CONSTRAINT chk_insight_edl_action CHECK (action_type IN (
        'SET_STATE', 'INCREMENT_VALUE', 'MERGE_PAYLOAD', 'CASCADE_TRIGGER', 'LOCK_NODE', 'RAISE_ERROR'
    ))
);

-- Seed Baseline EDL Rules
INSERT INTO insight_edl_rules (rule_code, rule_name, source_node_id, event_type, condition_expr, target_node_list, action_type, action_params)
VALUES ('EDL_R01', 'Node 1 Ingestion Cascade', 1, 'ON_TRIGGER', 'stateValue >= 0', '2,3,4', 'CASCADE_TRIGGER', '{"boostValue": 15, "status": "PROCESSING"}');

INSERT INTO insight_edl_rules (rule_code, rule_name, source_node_id, event_type, condition_expr, target_node_list, action_type, action_params)
VALUES ('EDL_R02', 'Node 4 Schema Validation Threshold', 4, 'ON_THRESHOLD_EXCEEDED', 'stateValue > 50', '9,10,11,12', 'SET_STATE', '{"targetStatus": "ACTIVE", "setValue": 85}');

INSERT INTO insight_edl_rules (rule_code, rule_name, source_node_id, event_type, condition_expr, target_node_list, action_type, action_params)
VALUES ('EDL_R03', 'Writeback Synchronizer', 12, 'ON_STATE_CHANGE', 'stateValue > 70', '20,21,24,26', 'MERGE_PAYLOAD', '{"sync_mode": "IMMEDIATE_WRITEBACK"}');

COMMIT;
